### ISSUE TITLE
Create a "Dark Mode"

### ISSUE THREAD

**Issue by giles-v** [giles-v/ghost-theme-dont-die#1]
The basic principle is that this will invert the reading colors of the site. White text on black. There may need to be other touchpoints which should be addressed.

The switcher will be something which is prominently available (maybe a fixed position element?) and especially on mobile. 

We should save the choice in a cookie to avoid the user needing to re-set it.

If desired, we could automatically set this based on time of day (sundown calculation).

**Comment by giles-v** [comment]
Implemented in https://github.com/giles-v/ghost-theme-dont-die/pull/10; deployed June 9, 2017 @ 10:25am EST.

@davidwolinsky please review the results and leave any comments here.

**Comment by davidwolinsky** [comment]
Hey!👍

We're in the process of migrating and fixing lots of things, but this menu
overall -- I honestly question whether people even see / know it's there.

**Comment by giles-v** [comment]
For sure! OK so two questions:

1. Is the dark mode good? Comments on the actual colors used, etc? Any parts I've missed? Probably worth using it in bed at night and seeing how it feels.
2. Where should we put this? Right now you have two header elements, the top logo and the top menu. I could make the menu persistent (always on screen) or I could also shift the dark mode switch out of that, so that it's a moon / sun at the top of the page by the burger.
3. Also didn't address / consider just doing an automatic switch based on time of day - looking at sunset ish times on your device's clock and auto-switching unless someone manually changes it. Thoughts on that?

**Comment by davidwolinsky** [comment]
Yeah man, this is awesome! I'll probably need to ping back when I've tried
it at night, but in the meantime:

1. Yes. Let me get back to you after trying it at night, but it's good.
Asked a few people and they all agreed.

2. Wonder if as an interim solution to save the bigger work for down the
road, it might make more sense just to make the menu persistent. // If we
could also throw a link to the Medium stuff on that menu, which lives at:
https://medium.com/@davidwolinsky. Is there another term we can use so it
doesn't just link on the word Medium so it doesn't seem like an ad for
Medium?

3. I think the auto-switch is pretty neat, and leaving it as a manual
switch either way will prompt people to look at the menu / change it / be
aware of the menu. Is that a ton of work?
