### ISSUE TITLE
Interview Pages: Including dates

### ISSUE THREAD

**Issue by davidwolinsky** [giles-v/ghost-theme-dont-die#23]
Basically as-is from a reader's suggestion:

![image](https://user-images.githubusercontent.com/6163541/30598325-40515a98-9d0e-11e7-8480-e0e0863d41c6.png)

Unless this is a horrible idea, let's side-step the bigger meta-data conversations about indexing interviews, how things will be linked together and searchable, etc. . . It obviously ties into search in some form, but for now let's focus on just a way to let people know what date each interview originally took place. I don't know what that text should literally be, and am wondering if it might be TMI to have posted date / conducted date. Maybe we do just call it "Published:" and "Interview Conducted:" 

Do you have suggestions on where the best place to place this might be? I suspect it ties into that ["illuminated manuscript" idea I had for the site](https://github.com/giles-v/ghost-theme-dont-die/issues/13), as it would fit there along with other miscellany important junk. By itself, I'm less sure other than literally just some place at the very top.

How would this work when deployed? Would there be a new field for me to fill in on Ghost? Or does Ghost not let you tweak its guts like that?

**Comment by giles-v** [comment]
@nlattessi I think this one should be an easy one, now that the data is (partially) provided. Can you handle?

**Comment by nlattessi** [comment]
@giles-v Yes, no problem!

**Comment by nlattessi** [comment]
I added it below date field with titles: _Published_ and _Conducted_. It looks like this:

![conducted](https://user-images.githubusercontent.com/5870496/69973575-7ed18680-1502-11ea-919a-e17a78d8d315.png)

What do you think?

**Comment by nlattessi** [comment]
@giles-v https://bitbucket.org/dontdie/dontdie-symfony/pull-requests/9/add-conducted-date-to-posts/diff

**Comment by nlattessi** [comment]
Merged changes to master! :+1:
