### ISSUE TITLE
Update Ghost to 1.x branch

### ISSUE THREAD

**Issue by giles-v** [giles-v/ghost-theme-dont-die#25]
@davidwolinsky: I think I need to make this priority. I'm working on some search stuff but it's all 1.x at this stage. I've sent Ghost an email and I think the most I will need from you is probably to set up a parallel 1.x account to migrate _into_, and a content freeze for a day or two while I get things over.

For now though, this is just to flag it up. I'll say the word as and when we actually need that.

**Comment by davidwolinsky** [comment]
Okay, keep me posted. Thanks for letting me know!

I'm back in LA (was out in the desert all weekend, far away from internet
signal and computers) but am more in the loop and routine of staying on top
of stuff. Occurred to me, if you need my cell I'm 312-608-6549, for web
emergencies or whatever.
