### ISSUE TITLE
Main page: Tagline with cycling text.

### ISSUE THREAD

**Issue by davidwolinsky** [giles-v/ghost-theme-dont-die#4]
So one of the No. 1 challenges of shepherding an interview series project about videogames that isn't literally only about videogames is communicating to readers when they get to the site that really there are a number of focuses I'm continually raking over. 

Whatever form the main page takes, want to make the "surviving videogames" in the tagline intermittently glitch or shift on its own so people can see the other topics the site is about surviving: 

- consumer culture
- social media
- the internet
- media apathy

There are likely others to add to this list, but this is a good starting point.

**Comment by giles-v** [comment]
@davidwolinsky this should be done now. please check and LMK if it works for you.

**Comment by davidwolinsky** [comment]
This is great! Do you have suggestions of other themes / things to add? I'm
all ears.

**Comment by giles-v** [comment]
We have other things in emails and I'm working on Search next. Let's keep that discussion by email / other tickets for now.

**Comment by davidwolinsky** [comment]
Sure!

I meant, re: suggestions to add as far as thematic throughlines in the
interviews to add to this specific marquee!

**Comment by giles-v** [comment]
Oh, haha, my apologies :-)

You mean peer data to "surviving video games" and "cultural apathy". Like, "the fault line between tech and humanity". Or something. I have no specific ideas, apart from that I think 4-5 is a good number of them to have.

**Comment by davidwolinsky** [comment]
Okay, cool. Wanted to ask!

"Media apathy," per our other thread, always makes me feel a little twinge
of Gamergate sympathy and wish there was a better way to phrase it. . . if
you have suggestions *there*, let me know.
