### ISSUE TITLE
Social buttons: no numbers

### ISSUE THREAD

**Issue by davidwolinsky** [giles-v/ghost-theme-dont-die#8]
This is open for discussion / debate, but I loathe the thinking with articles / posts online that the most traffic somehow suggests the "best" pieces. There might be a smarter implementation of sharing buttons on each interview, but regardless of what we wind up with I don't want to have counters on them so people can see how many times it was shared on Facebook, tweeted, etc. 

Low low priority but something I always am reminded I want to have for the site.

**Updating with specific things**:
- [x] Remove numbers from social buttons
- [ ] Add a Tumblr button
- [x] Move away from AddThis
- [ ] Add contextual social interaction buttons e.g. Tweet Quote
- [ ] Allow tweeting / sharing of quote-pics _a la_ pullquote.com.
- [ ] Make quote image tweets have badass branding / style

**Comment by giles-v** [comment]
I feel we could do better in general on the social stuff. Questions:

* They use AddThis; do you use any of the value-add that AddThis gives? Basically, analytics, and relatively lesser-known integrations (never heard of Pocket before). If not, then I suggest we streamline away from it.
* For stuff like Facebook, my sense (I don't have data, whomp whomp) is that having a "Like" button is much lower-friction than the FB share option you have now. But that would be 100% vanilla FB graphics / styling.

Thoughts?

**Comment by davidwolinsky** [comment]
I agree, I think we can do much better on the social stuff. I don't pay
particularly close attention to analytics in general, but that's something
I want to change on my end post-Ghost. Would it help if I shared you on the
Analytics to figure out how to do better?

Have never used AddThis, though Pocket, funny enough, is what I happen to
personally use all the time -- it's like Instapaper,  What would you
recommend instead? I think the option to be able to share passages is a
plausible use case, though what I usually see is people screengrabbing
large swathes and tweeting them and commenting that way.

I'm cool with revamping the way people can share, but I want to obscure the
perceived popularity contest. It really doesn't matter to a reader how
often thing X was broadcast onto channel Y. But I'd like to give them the
option to do so.

**Comment by davidwolinsky** [comment]
New request under this header in the short-term: Add a Tumblr option for folks.

In the long-term: We had started to talk about analytics stuff, let me know what you recommend when you get a chance to dig into it. Thanks!

**Comment by davidwolinsky** [comment]
You had suggested tweaking this share suite in general, and I wonder if this might be a good direction to go in. Was using a legal database to begin research on a new story that'll hopefully get the green light, and they make a menu pop up when you select text. Would a similar approach make sense for us, populated with different options than what's shown here? 

![screenshot 2017-06-14 at 5 01 38 pm](https://user-images.githubusercontent.com/6163541/27156561-31462844-5123-11e7-85a2-ae3ce0d34651.png)

**Comment by giles-v** [comment]
Updated checklist at the top with a couple of items.

@davidwolinsky

**Comment by giles-v** [comment]
@davidwolinsky do we consider this a priority still? If so, what are your most immediate needs?

**Comment by davidwolinsky** [comment]
My gut is no not really. . . maybe adding a Facebook "like" would be a nice
to have, though I am not sure if that is still preferable over the Facebook
"share" option?

**Comment by giles-v** [comment]
OK, I'm going to close this for now. We can definitely add fb-like if you want it. Picked share originally because it's more customizable, but Like is lower-friction so would be happy to have it.
